@MTask("NetTask", "Task")
class NetworkTask

  public function nodeRun(args)
    instance = new NetworkTask(args.url)
    instance.url = args.url
    return instance.run()
  end function

  public url = ""

  function new(url)
    m.url = url
  end function

  function doswttuff()
  end function

  function run()
    'fetch metadata
    'do reuest for profile
    'do request for entitelments
    'check purchases
    'return final collection
  end function
end class